### ISSUE TITLE
В бд не хватает файлов

### ISSUE THREAD

**Issue by shadr** [EXBO-Studio/stalcraft-database#10]
В базе данных не хватает файлов из-за возможной коллизии в именах файлов на файловых системах без учёта регистра. Я нашёл 3 предмета у которых не хватает как иконок так и json файла. Первый это **RQxk**(Поношенный «Изумруд») коллиззия с **RQXk**(КИМ-85Д) в категории *armor/scientist*. Второй и трейтий это **R2ZD**(Беличьи дрожжи) и **r2Zd**(Маячок группы «Гамма») коллиззия с **R2zD**(Очищенное вещество 07270) в категории *other*.

**Comment by abvadabra** [comment]
Исправлено в обновлениях 23-02-22: 6b588301f7da835b4c6ffeb8048ef7ffed909d50 и b39f907872453722707ab0d0902d384ec4283fec
