### ISSUE TITLE
Missing and inconsistent data

### ISSUE THREAD

**Issue by zaneshaw** [EXBO-Studio/stalcraft-database#8]
The database contains a lot of outdated/missing data in a lot of places. Outdated values suchs as weigths, artifact properties, etc are a quite common occurence. As well as a lack of numerical value distinction (i.e. integers, percentages and kgs are all stored as integer values). Developing a parser for this database has served to be a very difficult task. I could also see this being very inconvenient for wiki maintainers, as incorrect information isn't very useful.
Will there be an update soon addressing this issue?

Note: Missing/outdated data is consistent between both realms (global and ru)

**Comment by abvadabra** [comment]
We've update the database today, now it schould include latest information about items. We've also added pre-formatted parameter string, it should make it easier to display percentages/kgs/etc.

**Comment by zaneshaw** [comment]
Thank you :D
